INSERT INTO users (name,age) VALUES ("bob", 37);
INSERT INTO users (name,age) VALUES ("jill", 18);
INSERT INTO users (name,age) VALUES ("karl", 55);
INSERT INTO users (name,age) VALUES ("kate", 22);
INSERT INTO users (name,age) VALUES ("sha", 34);
INSERT INTO users (name,age) VALUES ("karen", 18);
INSERT INTO users (name,age) VALUES ("steve", 25);
INSERT INTO users (name,age) VALUES ("lily", 28);
INSERT INTO users (name,age) VALUES ("sharon", 30);
INSERT INTO users (name,age) VALUES ("janice", 18);
INSERT INTO users (name,age) VALUES ("holly", 18);
INSERT INTO users (name,age) VALUES ("riva", 64);
INSERT INTO users (name,age) VALUES ("derek", 18);
INSERT INTO users (name,age) VALUES ("nate", 54);
INSERT INTO users (name,age) VALUES ("phil", 18);
INSERT INTO users (name,age) VALUES ("david", 33);
INSERT INTO users (name,age) VALUES ("sally", 44);
INSERT INTO users (name,age) VALUES ("norma", 18);
INSERT INTO users (name,age) VALUES ("erma", 63);
INSERT INTO users (name,age) VALUES ("john", 32);

INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ("t1","c2","fd1","jan1","dec1");

INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);
INSERT INTO pledges (amount,user_id,project_id) VALUES (1,2,3);

