INSERT INTO users (name, age) VALUES ('Scott', 29);
INSERT INTO users (name, age) VALUES ('Mary', 33);
INSERT INTO users (name, age) VALUES ('Rebecca', 27);
INSERT INTO users (name, age) VALUES ('Zander', 29);
INSERT INTO users (name, age) VALUES ('Erika', 35);
INSERT INTO users (name, age) VALUES ('Henry', 40);
INSERT INTO users (name, age) VALUES ('Charles', 70);
INSERT INTO users (name, age) VALUES ('Amelia', 70);
INSERT INTO users (name, age) VALUES ('Christian', 33);
INSERT INTO users (name, age) VALUES ('Christina', 32);
INSERT INTO users (name, age) VALUES ('Will', 31);
INSERT INTO users (name, age) VALUES ('Mike', 29);
INSERT INTO users (name, age) VALUES ('David', 24);
INSERT INTO users (name, age) VALUES ('Aaron', 22);
INSERT INTO users (name, age) VALUES ('Anthony', 65);
INSERT INTO users (name, age) VALUES ('Maryann', 60);
INSERT INTO users (name, age) VALUES ('Eva', 58);
INSERT INTO users (name, age) VALUES ('Tim', 55);
INSERT INTO users (name, age) VALUES ('Rose', 26);
INSERT INTO users (name, age) VALUES ('Abby', 25);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('The Wide Awakes', 'art', 100000, '06/05/20', '10/8/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Keep NYC's Lights On", 'art', 20000, '05/20/20', '10/17/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Patience", 'comics', 12000, '2/6/20', '10/2/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hereditary", 'film', 150000, '03/12/20', '11/17/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Witch", 'film', 200000, '03/5/20', '12/15/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Minesweeper", 'games', 10000, '01/15/20', '11/20/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Solitair", 'games', 30000, '04/20/20', '9/17/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Stranger", 'publishing', 13000, '01/20/20', '7/12/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save Britney", 'music', 200000, '02/28/20', '6/5/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("99 Problems", 'music', 60000, '06/20/20', '7/20/20');

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 2, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 2, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 2, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 3, 2);